Repository JoComp27/SOEN341-SA1, pull requests merged in 2018-02, with the labels that each got.

#46 #32 User Story 4: FrontEnd
  App/PHP_HTML/answer.php
  App/PHP_HTML/answer_state.php
  App/index.php
  index.php
Labels: Sprint 2

#47 #39 - SA1#5 adding travisCI
  .travis.yml
Labels: Must haves, Sprint 2

#77 T3.1 - Voting system for answers
  .travis.yml
  App/PHP_HTML/Answer/answer.php
  App/PHP_HTML/Home Page/home.html
  App/PHP_HTML/answer.php
  App/PHP_HTML/answer_state.php
  App/PHP_HTML/ask_question.css
  App/PHP_HTML/ask_question.js
  App/PHP_HTML/ask_question.php
  App/PHP_HTML/decrementalVoting.php
  App/PHP_HTML/header.php
  App/PHP_HTML/home.php
  App/PHP_HTML/incrementalVoting.php
  App/PHP_HTML/login sample/logo.png
  App/PHP_HTML/login sample/signIn.html
  App/PHP_HTML/login sample/signUp.css
  App/PHP_HTML/login sample/signUp.html
  App/PHP_HTML/login sample/signUp.php
  App/PHP_HTML/question_submission.php
  App/PHP_HTML/sql_connector.php
  App/SQL_DB/sprint_2_create_tables_query.sql
  App/connection.php
  App/index.php
  README.md
  index.php
Labels: Sprint 2, USER STORY 3

#81 Header.php updated for calling search.php #68
  App/PHP_HTML/header.php
Labels: Sprint 3

#82 search.php file created for issue #68
  App/PHP_HTML/search.php
Labels: Sprint 3

#85 Added Composer & TravisCI fixes without changing the APP to src dir.
  .gitignore
  .travis.yml
  App/Tests/phpunit.php
  Autoloading example.txt
  composer.json
  composer.lock
  phpunit.xml
Labels: Must haves, Sprint 2, ~USER STORY~

#89 #54: Fixed issue where answer states were not properly saved upon submission
  App/PHP_HTML/answer_state.php
  App/PHP_HTML/answer_state_2.php
Labels: Must haves, Sprint 3

#90 #79 added home.css modified header.php and home.php
  App/PHP_HTML/header.php
  App/PHP_HTML/home.css
  App/PHP_HTML/home.php
Labels: Sprint 3, USER STORY 7

#91 #79 Front end Animated Ask Question Button
  App/PHP_HTML/ask_question.css
  App/PHP_HTML/home.php
Labels: Sprint 3, USER STORY 7
