Repository JoComp27/SOEN341-SA1, pull requests merged in 2018-03, with the labels that each got.

#105 #104, Task #3.1 Adding architecture diagram
  architecture_diagram.png
Labels: Sprint 3, ~USER STORY~

#107 #106 - Applied Reformatting for the current master build
  App/PHP_HTML/answer.php
  App/PHP_HTML/answer_state.php
  App/PHP_HTML/answer_state_2.php
  App/PHP_HTML/ask_question.css
  App/PHP_HTML/ask_question.js
  App/PHP_HTML/decrementalVoting.php
  App/PHP_HTML/header.php
  App/PHP_HTML/home.css
  App/PHP_HTML/home.php
  App/PHP_HTML/incrementalVoting.php
  App/PHP_HTML/login sample/check_login.php
  App/PHP_HTML/login sample/notification.php
  App/PHP_HTML/login sample/signIn.css
  App/PHP_HTML/login sample/signIn.php
  App/PHP_HTML/login sample/signIn_1.php
  App/PHP_HTML/login sample/signIn_2.php
  App/PHP_HTML/login sample/signIn_Submission.php
  App/PHP_HTML/login sample/signOut_Submission.php
  App/PHP_HTML/login sample/signUp.css
  App/PHP_HTML/login sample/signUp.php
  App/PHP_HTML/login sample/test.php
  App/PHP_HTML/notification.css
  App/PHP_HTML/notification.php
  App/PHP_HTML/notification_view_message.php
  App/PHP_HTML/question_submission.php
  App/PHP_HTML/search.php
  App/PHP_HTML/sql_connector.php
  App/Tests/phpunit.php
  composer.json
  index.php
  phpunit.xml
Labels: Sprint 3, ~USER STORY~

#103 #69 SA1 - Question Tags
  .gitignore
  App/PHP_HTML/header.php
  App/PHP_HTML/home.php
  App/PHP_HTML/login sample/signUp.php
  App/PHP_HTML/question_submission.php
  App/PHP_HTML/tag.php
  App/SQL_DB/sprint_3_create_tables_query.sql
  BootstrapLibrary/BootstrapTags/bootstrap-tagsinput.css
  BootstrapLibrary/BootstrapTags/bootstrap-tagsinput.js
Labels: Sprint 3, ~USER STORY~

#109 #65 - User Story 1 Sprint 3: Profile Page for users
  App/PHP_HTML/header.php
  App/PHP_HTML/login sample/profile.php
  App/PHP_HTML/login sample/signIn_Submission.php
  App/PHP_HTML/profile.php
Labels: Sprint 3, ~USER STORY~

#111 #110 Added Test configs for the testing environment of the project (Do not merge yet! - Made Pull request to config TravicCI)
  .travis.yml
  App/Tests/OneTest.php
  composer.json
  composer.lock
  phpunit.xml
Labels: Must haves, Sprint 3

#114 #110 Adding database config files for Travis
  .travis.yml
  config/database.yml
Labels: Must haves, Sprint 3

#112 #110 : Adding unit testing for ask question, session, sql connector (Dependency on JoComp27's pull request #111, merge AFTER merging #111)
  .travis.yml
  A.php
  App/PHP_HTML/login sample/signOut_Submission.php
  App/Tests/ConnectorTest.php
  App/Tests/QuestionTest.php
  App/Tests/SessionTest.php
  App/Tests/sprint_3_create_tables_query.sql
  phpunit.xml
Labels: Must haves, Sprint 3

#117 #116 Ensure the styling holds up on window resizing
  App/PHP_HTML/login sample/signIn_1.php
  App/PHP_HTML/login sample/signUp.css
  App/PHP_HTML/login sample/signUp.php
Labels: Sprint 3, TASK, USER STORY 7

#108 #71 UserStory 6 Sprint 3 : Forgot Password File along with Pop-Ups for logging in
  App/PHP_HTML/login sample/check_login.php
  App/PHP_HTML/login sample/forgotPassword.php
  App/PHP_HTML/login sample/signIn_1.php
  App/PHP_HTML/login sample/signIn_2.php
Labels: Sprint 3, ~USER STORY~

#113 #65: Profile Page Update
  App/PHP_HTML/answer.php
  App/PHP_HTML/profile.php
Labels: Sprint 3, USER STORY 1

#121 Task 3.3.1 - User Can Delete A Question
  App/PHP_HTML/answer.php
  App/PHP_HTML/answer_state.php
  App/PHP_HTML/deleteQuestion/delete_question_action.php
  App/PHP_HTML/deleteQuestion/delete_question_view.php
  App/PHP_HTML/home.php
Labels: Sprint 3, TASK, USER STORY 3

#136 Master-Fix - Changes the redirect in Question submission
  App/PHP_HTML/question_submission.php
Labels: Must haves, Sprint 3, Sprint 4

#138 #131 coding style refactoring for Displaying Questions
  .gitignore
  App/PHP_HTML/Display_Questions.php
  App/PHP_HTML/home.php
  App/PHP_HTML/login sample/signIn_Submission.php
  App/PHP_HTML/login sample/signUp.php
  App/PHP_HTML/tag.php
  index.php
Labels: Sprint 3, Sprint 4, TASK

#143 #131 - Fix for the Tag query
  App/PHP_HTML/tag.php
Labels: Must haves, Sprint 3, bug

#144 #133 User Can Modify An Answer [ FIX ]
  App/PHP_HTML/answer.php
  App/PHP_HTML/modifyAnswer/answerForm.js
  App/PHP_HTML/modifyAnswer/modify_answer_action.php
  App/PHP_HTML/modifyAnswer/modify_answer_view.php
Labels: bug

#147 #148 fixed answer state button view
  App/PHP_HTML/answer_state.php
Labels: Sprint 4, TASK

#153 #152 - BUG: Fix Issues with SQL Query File
  App/SQL_DB/sprint_4_create_tables_query.sql
Labels: Sprint 4, bug

#155 #65 - Fixed issues with User Profile Page
  App/PHP_HTML/answer.php
  App/PHP_HTML/login sample/profile.php
  App/PHP_HTML/profile.php
Labels: Sprint 3, Sprint 4, enhancement

#166 #146 upvote&downvote questions
  App/PHP_HTML/Display_Questions.php
  App/PHP_HTML/answer.php
  App/PHP_HTML/decrementalVoting.php
  App/PHP_HTML/fillQuestionForm.js
  App/PHP_HTML/header.php
  App/PHP_HTML/home.php
  App/PHP_HTML/incrementalVoting.php
  App/PHP_HTML/questionDecrementalVoting.php
  App/PHP_HTML/questionIncrementalVoting.php
  App/PHP_HTML/question_form_view.php
  App/SQL_DB/sprint_3_create_tables_query.sql
  App/SQL_DB/sprint_4_create_tables_query.sql
Labels: Sprint 4, ~USER STORY~

#167 #165 BUG - Profile page does not display certain user information
  App/PHP_HTML/answer.php
  App/PHP_HTML/login sample/check_login.php
  App/PHP_HTML/profile.css
  App/PHP_HTML/profile.php
  App/PHP_HTML/question_submission.php
  App/SQL_DB/sprint_4_create_tables_query.sql
Labels: Sprint 4, bug

#169 #168 Only User Who Created The Question Can Accept/Decline An Answer
  App/PHP_HTML/answer.php
  App/PHP_HTML/answer_state_action.php
  App/PHP_HTML/answer_state_view.php
Labels: Sprint 4, TASK
